### PR TITLE
Trying to make it work

### PR DESCRIPTION
**Pull request by dchaplinsky**

### CODE REVIEW

**Comment by excieve** [comment]
Same (or maybe even better in terms of lookup performance) can be done by properly indexing the pandas dataframe when reading the table:
```.py
df = pandas.read_csv(filename, index_col=match_field)
```
After that rows can be matched by ID directly. Here's what works fast enough for me. In `map_row_to_esop` function:
```.py
doc['couchdb_id'] = doc.pop('_id')  # ES doesn't allow "_id" as it is its own metadata
try:
    processed_doc = processed.loc[doc['doc_uuid']]
    # Getting rid of numpy types before passing over to ES JSON serialiser
    doc[container_field] = dict(
        (k, np_to_scalar(v)) for k, v in processed_doc.items()
    )
except KeyError:
    pass
```

Also it's probably worth decreasing the batch sizes somewhat. Not sure what are the good values really (ideally they should be configurable). But for 16 threads to be busy and keep the ES request time within the 10s something like `limit=4800` and `chunk_size=300` seems to be fine.

**Comment by dchaplinsky** [comment]
I've tried indexing, performance was roughly the same as in your initial implementation. Maybe I did it wrong, will try your code (will appreciate if you can commit it to the branch).

Speaking of loading that to ES. In all my tests, key bottleneck was lookup time, not ES itself. Even the last version (80 minutes for 1.5m documents) only managed to heat the server to LA of 1-2.

**Comment by excieve** [comment]
With my changes, 1.15M records pumped in 45m with LA ≈5;6;6 and ES consuming the most. This is with 10 threads (higher seems to break the connection pool by default when there's no bottleneck), 300 chunk size and 3000 docs loaded from couch at once. This is on Ryzen 1700X (8C/16T), 32GB RAM and settings from docker-compose. Will push these changes tomorrow but they're really outlined in the previous comment.

**Comment by excieve** [comment]
Total of 1472019 pumped in:
```
real	63m15,587s
user	0m1,032s
sys	0m0,240s
```

**Comment by dchaplinsky** [comment]
Looks good! Waiting for a push!

**Pull request merged**
